export type StockStatus = 'disponible' | 'bajo-stock' | 'agotado' | 'por-vencer' | 'descontinuado'|'vencido';

export interface Producto {
  id: string;
  sku: string;
  nombre: string;
  laboratorio: string;
  categoria: string;
  stockActual: number;
  stockMinimo: number;
  precioCompra: number;
  precioVenta: number;
  fechaVencimiento: string;
  lote: string;
  status: StockStatus;
  controlado: boolean;
  
  
}

export const categorias = [
  'Todas',
  'Analgésicos',
  'Antibióticos',
  'Vitaminas y Suplementos',
  'Antiácidos',
  'Antihipertensivos',
  'Dermatología',
  'Antidiabéticos',
  'Antihistamínicos',
];

export const productos: Producto[] = [
  {
    id: 'prod-001',
    sku: 'MED-0042',
    nombre: 'Paracetamol 500mg x 20 tab',
    laboratorio: 'Pharmabrand',
    categoria: 'Analgésicos',
    stockActual: 342,
    stockMinimo: 100,
    precioCompra: 1.20,
    precioVenta: 2.50,
    fechaVencimiento: '2027-08-15',
    lote: 'L2025-881',
    status: 'disponible',
    controlado: false,
  },
  {
    id: 'prod-002',
    sku: 'MED-0091',
    nombre: 'Amoxicilina 500mg x 21 cap',
    laboratorio: 'MediLab',
    categoria: 'Antibióticos',
    stockActual: 187,
    stockMinimo: 80,
    precioCompra: 3.40,
    precioVenta: 6.80,
    fechaVencimiento: '2026-11-30',
    lote: 'L2025-442',
    status: 'disponible',
    controlado: false,
  },
  {
    id: 'prod-003',
    sku: 'MED-0154',
    nombre: 'Metformina 850mg x 30 tab',
    laboratorio: 'GenFarma',
    categoria: 'Antidiabéticos',
    stockActual: 12,
    stockMinimo: 50,
    precioCompra: 2.80,
    precioVenta: 5.40,
    fechaVencimiento: '2027-03-20',
    lote: 'L2025-319',
    status: 'bajo-stock',
    controlado: false,
  },
  {
    id: 'prod-004',
    sku: 'MED-0203',
    nombre: 'Losartán 50mg x 30 tab',
    laboratorio: 'Pharmabrand',
    categoria: 'Antihipertensivos',
    stockActual: 63,
    stockMinimo: 40,
    precioCompra: 4.10,
    precioVenta: 8.20,
    fechaVencimiento: '2026-06-01',
    lote: 'L2025-114',
    status: 'por-vencer',
    controlado: false,
  },
  {
    id: 'prod-005',
    sku: 'MED-0267',
    nombre: 'Ibuprofeno 400mg x 20 tab',
    laboratorio: 'MediLab',
    categoria: 'Analgésicos',
    stockActual: 521,
    stockMinimo: 150,
    precioCompra: 1.60,
    precioVenta: 3.20,
    fechaVencimiento: '2028-01-10',
    lote: 'L2026-441',
    status: 'disponible',
    controlado: false,
  },
  {
    id: 'prod-006',
    sku: 'MED-0312',
    nombre: 'Vitamina C 1000mg x 30 tab',
    laboratorio: 'NutriPharma',
    categoria: 'Vitaminas y Suplementos',
    stockActual: 0,
    stockMinimo: 60,
    precioCompra: 3.90,
    precioVenta: 7.80,
    fechaVencimiento: '2027-06-30',
    lote: 'L2025-667',
    status: 'agotado',
    controlado: false,
  },
  {
    id: 'prod-007',
    sku: 'MED-0388',
    nombre: 'Atorvastatina 20mg x 30 tab',
    laboratorio: 'GenFarma',
    categoria: 'Antihipertensivos',
    stockActual: 94,
    stockMinimo: 30,
    precioCompra: 5.20,
    precioVenta: 10.40,
    fechaVencimiento: '2027-09-15',
    lote: 'L2025-553',
    status: 'disponible',
    controlado: false,
  },
  {
    id: 'prod-008',
    sku: 'MED-0421',
    nombre: 'Omeprazol 20mg x 28 cap',
    laboratorio: 'Pharmabrand',
    categoria: 'Antiácidos',
    stockActual: 228,
    stockMinimo: 60,
    precioCompra: 2.30,
    precioVenta: 4.60,
    fechaVencimiento: '2026-05-28',
    lote: 'L2025-228',
    status: 'por-vencer',
    controlado: false,
  },
  {
    id: 'prod-009',
    sku: 'MED-0499',
    nombre: 'Loratadina 10mg x 10 tab',
    laboratorio: 'MediLab',
    categoria: 'Antihistamínicos',
    stockActual: 34,
    stockMinimo: 80,
    precioCompra: 1.80,
    precioVenta: 3.60,
    fechaVencimiento: '2027-12-01',
    lote: 'L2025-778',
    status: 'bajo-stock',
    controlado: false,
  },
  {
    id: 'prod-010',
    sku: 'MED-0542',
    nombre: 'Clotrimazol Crema 1% 20g',
    laboratorio: 'DermaLab',
    categoria: 'Dermatología',
    stockActual: 76,
    stockMinimo: 25,
    precioCompra: 3.10,
    precioVenta: 6.20,
    fechaVencimiento: '2028-03-15',
    lote: 'L2026-102',
    status: 'disponible',
    controlado: false,
  },
  {
    id: 'prod-011',
    sku: 'MED-0601',
    nombre: 'Tramadol 50mg x 10 cap',
    laboratorio: 'GenFarma',
    categoria: 'Analgésicos',
    stockActual: 28,
    stockMinimo: 20,
    precioCompra: 4.50,
    precioVenta: 9.00,
    fechaVencimiento: '2027-07-20',
    lote: 'L2025-991',
    status: 'disponible',
    controlado: true,
  },
  {
    id: 'prod-012',
    sku: 'MED-0658',
    nombre: 'Salbutamol Inhalador 100mcg',
    laboratorio: 'RespiMed',
    categoria: 'Antihistamínicos',
    stockActual: 0,
    stockMinimo: 15,
    precioCompra: 6.80,
    precioVenta: 13.60,
    fechaVencimiento: '2027-02-28',
    lote: 'L2025-404',
    status: 'agotado',
    controlado: false,
  },
];